In [29]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\Users\5406\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\5406\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.5.3)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\5406\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\5406\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\5406\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\5406\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\Users\5406\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

In [30]:
#Loading and exploring iris
import numpy as np
from sklearn.datasets import load_iris

iris=load_iris()

X=iris.data
y=iris.target

print("Features name:", iris.feature_names)
print("Class names:",iris.target_names)
print("X SHape:",X.shape)
print("y shape:",y.shape)

print("FIrst 5 samples:",X[:5])
print("First 5 Labels:",y[:5])

Features name: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Class names: ['setosa' 'versicolor' 'virginica']
X SHape: (150, 4)
y shape: (150,)
FIrst 5 samples: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
First 5 Labels: [0 0 0 0 0]

In [31]:
#Seeing it as a df or a table instead of a series
import pandas as pd

df=pd.DataFrame(iris.data,columns=iris.feature_names)
df["targets"] = iris.target
df["species"] = iris.target_names[iris.target]

display(df.head(10))
print(df.head(10))
df.sort_values(by="sepal length (cm)",axis=0,inplace=False)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),targets,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa
5,5.4,3.9,1.7,0.4,0,setosa
6,4.6,3.4,1.4,0.3,0,setosa
7,5.0,3.4,1.5,0.2,0,setosa
8,4.4,2.9,1.4,0.2,0,setosa
9,4.9,3.1,1.5,0.1,0,setosa

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

   targets species
0        0  setosa
1        0  setosa
2        0  setosa
3        0  setosa
4        0  setosa
5        0  setosa
6        0  setosa
7        0  setosa
8        0  setosa
9        0  setosa

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),targets,species
13,4.3,3.0,1.1,0.1,0,setosa
8,4.4,2.9,1.4,0.2,0,setosa
42,4.4,3.2,1.3,0.2,0,setosa
38,4.4,3.0,1.3,0.2,0,setosa
41,4.5,2.3,1.3,0.3,0,setosa
...,...,...,...,...,...,...
122,7.7,2.8,6.7,2.0,2,virginica
117,7.7,3.8,6.7,2.2,2,virginica
118,7.7,2.6,6.9,2.3,2,virginica
135,7.7,3.0,6.1,2.3,2,virginica
131,7.9,3.8,6.4,2.0,2,virginica

In [32]:
#Experimenting with random sample to build the logic
sample_df=df.sample(n=10,random_state=42)#This gives us a visualizable sample
sample_df.sort_values(by="sepal length (cm)", axis=0,inplace=False)
#Don't do easy and time consuming stuff like sorting manually

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),targets,species
31,5.4,3.4,1.5,0.4,0,setosa
64,5.6,2.9,3.6,1.3,1,versicolor
18,5.7,3.8,1.7,0.3,0,setosa
82,5.8,2.7,3.9,1.2,1,versicolor
78,6.0,2.9,4.5,1.5,1,versicolor
73,6.1,2.8,4.7,1.2,1,versicolor
68,6.2,2.2,4.5,1.5,1,versicolor
76,6.8,2.8,4.8,1.4,1,versicolor
141,6.9,3.1,5.1,2.3,2,virginica
118,7.7,2.6,6.9,2.3,2,virginica

In [33]:
#Splitting the data into training and testing
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=4,
    stratify=y
    )

print("Training data:",X_train.shape)
print("Testing data:",X_test.shape)

Training data: (120, 4)
Testing data: (30, 4)

In [34]:
#Function to calculate Gini Impurity
def Gini(labels):
    if(len(labels)==0):
        return 0
    species_list,occurances=np.unique(labels,return_counts=True)
    #This function  returns 2 np.arrays 

    proportions=occurances/len(labels)

    squared_sum=0
    for p in proportions:
        squared_sum+=(p**2)

    return 1-squared_sum

# return 1 - np.sum(proportions ** 2) ALITER

In [35]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [36]:
df["species"]
print(type(df["species"].to_numpy()))

<class 'numpy.ndarray'>

In [37]:
def decision_Tree(df):
    #base cases in recursion:
    if(len(df)<=20):
        names,counts=np.unique(df["species"].to_numpy(),return_counts=True)
        return str(names[np.argmax(counts)])
    if(df["species"].nunique()==1):
        return str(df["species"].iloc[0])
    
    best_gini=float("inf")
    best_j=None
    best_thershold=float("inf")
    final_treshold=None
    for j in range(X.shape[1]):
        avg=np.array([])
        Gini_array=np.array([])
        sorted_df=df.sort_values(by=df.columns[j])
        sorted_current_col=sorted_df.iloc[:,j]
        #current_col is  a series so by="" is not needed

        #This loop traverses through a col and each iteration corresponds
        #to each avearge we encounter
        for i in range(len(sorted_current_col)-1):
            if sorted_current_col.iloc[i] == sorted_current_col.iloc[i + 1]:
                continue
            #First calculate the i th average and store in an array
            thresh=(sorted_current_col.iloc[i]+sorted_current_col.iloc[i+1])/2
            avg=np.append(avg,thresh)
            #calculate gini impurity of left group
            label1=sorted_df["species"].iloc[:i+1].to_numpy()
            if(label1.size>0):
                g1=Gini(label1)
            #calculate gini impurity of right group
            label2=sorted_df["species"].iloc[i+1:].to_numpy()
            if(label2.size>0):
                g2=Gini(label2)
            #calculate weighted GI for i th avg and store in array
            Gini_array=np.append(Gini_array,((i+1)*g1 + (len(sorted_current_col)-i-1)*g2)/len(sorted_current_col))
        if len(Gini_array) == 0:
            continue
        min_GI=min(Gini_array)
        if(min_GI<best_gini):
            best_gini=min_GI
            best_j=j
            final_treshold=avg[np.argmin(Gini_array)]

    if best_j is None:
        names, counts = np.unique(df["species"], return_counts=True)
        return names[np.argmax(counts)] 
    
    best_sorted_df = df.sort_values(by=df.columns[best_j])
    #best_sorted_df is still a df
    k=0
    n=len(best_sorted_df)
    while(k<n and best_sorted_df.iloc[k,best_j]<=final_treshold):
        k+=1
    left_label=best_sorted_df.iloc[:k]
    right_label=best_sorted_df.iloc[k:]

    left_child=decision_Tree(left_label)
    right_child=decision_Tree(right_label)

    return {
        "feature": df.columns[best_j],
        "threshold":final_treshold,
        "left": left_child,
        "right": right_child
    }
#Only training data goes in this function.
#This function takes in input in the form of training df 
#And in output it builds the entire decision tree and 
#returns the dict of the root node.


    #print("best_gini=",best_gini)
    #print("best_j=",best_j)
    #print("final_treshold=",final_treshold)

In [39]:
tree=decision_Tree(df)
tree
#This is a dictionary as its function decision_Tree(df)
#returns a dictionary
#And this uses the whole df and is not split in training and testing

{'feature': 'petal length (cm)',
 'threshold': np.float64(2.45),
 'left': 'setosa',
 'right': {'feature': 'petal width (cm)',
  'threshold': np.float64(1.75),
  'left': {'feature': 'petal length (cm)',
   'threshold': np.float64(4.95),
   'left': {'feature': 'petal width (cm)',
    'threshold': np.float64(1.65),
    'left': 'versicolor',
    'right': 'virginica'},
   'right': 'virginica'},
  'right': {'feature': 'petal length (cm)',
   'threshold': np.float64(4.85),
   'left': 'virginica',
   'right': 'virginica'}}}

In [40]:
from sklearn.model_selection import train_test_split

train_df,test_df=train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["species"]#preserve each species proportions
)
#This means that when we give train_test_split a full table as 
#a df , it divides it into 2 dfs - one is for training and
#the other is for testing
print("Training row length:",len(train_df))
print("Testing row length:",len(test_df))

Training row length: 120
Testing row length: 30

In [41]:
train_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),targets,species
8,4.4,2.9,1.4,0.2,0,setosa
106,4.9,2.5,4.5,1.7,2,virginica
76,6.8,2.8,4.8,1.4,1,versicolor
9,4.9,3.1,1.5,0.1,0,setosa
89,5.5,2.5,4.0,1.3,1,versicolor
...,...,...,...,...,...,...
37,4.9,3.6,1.4,0.1,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
33,5.5,4.2,1.4,0.2,0,setosa
52,6.9,3.1,4.9,1.5,1,versicolor
3,4.6,3.1,1.5,0.2,0,setosa

In [42]:
def predict_one(f,t):
    '''
f represenst a single flower which has its features like
petal length, sepal length etc. and these are stored in a series 
called f and we are passing this as parameter as we require
features to predict something
'''
#When t is a leaf:(base case)
    if(type(t)!=dict):
        return t
    
#When t is not a leaf:
    feature=t["feature"]
    threshold = t["threshold"]

    if f[feature] <= threshold:
        return predict_one(f, t["left"])
    else:
        return predict_one(f, t["right"])

In [43]:
tree=decision_Tree(train_df)
tree#This is the decision tree that we made based on the 
#training data and this model is now trained
#Now we will test it using th etesting data

{'feature': 'petal length (cm)',
 'threshold': np.float64(2.45),
 'left': 'setosa',
 'right': {'feature': 'petal width (cm)',
  'threshold': np.float64(1.65),
  'left': {'feature': 'petal length (cm)',
   'threshold': np.float64(4.95),
   'left': 'versicolor',
   'right': 'virginica'},
  'right': {'feature': 'petal length (cm)',
   'threshold': np.float64(4.85),
   'left': 'virginica',
   'right': 'virginica'}}}

In [44]:
flower=test_df.iloc[3]
flower

sepal length (cm)           5.0
sepal width (cm)            2.3
petal length (cm)           3.3
petal width (cm)            1.0
targets                       1
species              versicolor
Name: 93, dtype: object

In [45]:
prediction=predict_one(flower,tree)
print(prediction)

versicolor

In [50]:
#Now testing all flowers
prediction=pd.DataFrame(columns=["Predicted species"])
for i in range(len(test_df)):
    prediction.loc[i,"Predicted species"]=predict_one(test_df.iloc[i],tree)

actual=test_df["species"].reset_index(drop=True).to_frame(name="Actual species")

comparision_tabe=pd.concat([actual,prediction],axis=1)
comparision_tabe

   Actual species Predicted species
0          setosa            setosa
1       virginica         virginica
2      versicolor        versicolor
3      versicolor        versicolor
4          setosa            setosa
5      versicolor        versicolor
6          setosa            setosa
7          setosa            setosa
8       virginica         virginica
9      versicolor        versicolor
10      virginica         virginica
11      virginica         virginica
12      virginica         virginica
13     versicolor        versicolor
14         setosa            setosa
15         setosa            setosa
16         setosa            setosa
17     versicolor        versicolor
18     versicolor        versicolor
19      virginica         virginica
20         setosa            setosa
21      virginica         virginica
22     versicolor        versicolor
23      virginica         virginica
24      virginica         virginica
25     versicolor         virginica
26     versicolor        versicolor
27         setosa            setosa
28      virginica         virginica
29         setosa            setosa

In [54]:
i=0
correct=0
#Calculating number of correct predictions
while(i<len(test_df)):
    if(actual.iloc[i,0]==prediction.iloc[i,0]):
        #Use iloc here as it is not a NumPy array but a pd df
        correct+=1
    i+=1

#Calculating accuracy
accuracy=str((correct/len(test_df))*100) +"%"
accuracy

'96.66666666666667%'

In [55]:
#Prediction based on user inputs for any random flower:
sepal_length = float(input("Sepal length (cm): "))
sepal_width = float(input("Sepal width (cm): "))
petal_length = float(input("Petal length (cm): "))
petal_width = float(input("Petal width (cm): "))

new_flower=pd.Series({
    "Sepal length (cm)":sepal_length,
    "sepal width (cm)": sepal_width,
    "petal length (cm)": petal_length,
    "petal width (cm)": petal_width
})

new_prediction=predict_one(new_flower,tree)

print("The prediction is:",new_prediction)

The prediction is: versicolor